/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kasus;

import org.hibernate.cfg.Configuration;
import org.hibernate.SessionFactory;
import org.hibernate.Session;
import java.util.Set;
import java.util.HashSet;
import java.util.List;

public class App {

    // config builder
    private static final Configuration cfg=new Configuration()
            .configure("hibernate.cfg.xml");
    //session factory builder
    private static final SessionFactory factory = cfg.buildSessionFactory();
    
    public static void main(String[] args) {
    
        // open session
        Session session = factory.openSession();
        session.beginTransaction();

        Salutation sal = new Salutation();
        sal.setId(1);sal.setSalutation("Mr. ");
        Salutation sal2 = new Salutation();
        sal2.setId(2);sal2.setSalutation("Ms. ");

        Movie mv = new Movie();
        mv.setId(1);mv.setTitle("Movie 1");
        Movie mv2 = new Movie();
        mv2.setId(2);mv2.setTitle("Purates");
        
        Member mem = new Member();
        mem.setId(1);mem.setFullName("Lazuardi");mem.setAddress("tegak");mem.getMovies().add(mv);
        mem.getMovies().add(mv2);mem.setSalutation(sal);
        Member mem2 = new Member();
        mem2.setId(2);mem2.setFullName("cikutar");mem2.setAddress("fsdfs");mem2.getMovies().add(mv);
        mem2.setSalutation(sal2);

        mv.getMembers().add(mem);mv.getMembers().add(mem2);
        mv.getMembers().add(mem);

        sal.getMembers().add(mem);
        sal.getMembers().add(mem2);

        session.save(mv);session.save(mv2);
        session.save(mem);session.save(mem2);
        session.save(sal);session.save(sal2);

        String hql = "from Member as m inner join m.salutation as salut";
        List<?> list = session.createQuery(hql).list();
        
        for(int i=0; i<list.size(); i++) {
			Object[] row = (Object[]) list.get(i);
			Member member = (Member)row[0];
			Salutation salut = (Salutation)row[1];
         
            //String hql2 = "select mo.title, mo.id "
            String hql3 = "from Member me join me.movies mo "
            +"where me.member_id="+member.getId();
            List<?> list2 = session.createQuery(hql3).list();
            System.out.println(salut.getSalutation()+" "+member.getFullName()+" rents:");
            for (int j = 0; j < list2.size(); j++) {
                Object[] row2 = (Object[]) list2.get(j);
                Member member2 = (Member) row[0];
                Movie movie = member2.getMovies().get(j);
                
                System.out.println(j+1+". "+movie.getTitle());
            }           
                       
		}
        
        session.getTransaction().commit();
        session.close();

    }
}
