micronaut:
  server:
      cors:
          enabled: true

  application:
    name: buku
    
---
graphql:
  graphiql:
    enabled: true
    version: 0.13.2
    path: /graphiql
    template-path: classpath:graphiql/index.html
    template-parameters:
      page-title: GraphiQL
  enabled: true 
  path: /graphql 
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/coba
    username: akbarlaz
    password: "password"
    driverClassName: org.mariadb.jdbc.Driver
jpa:
  default:
    packages-to-scan:
      'buku'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          show_sql: true
application:
  max: 50