/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latihan;

import latihan.mongodb.*;
import latihan.cockroachdb.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        //InsertingDocument obj = new InsertingDocument();
        //obj.main(args);
    
        BasicExample obj = new BasicExample();
        obj.main(args);

    }


}
