/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package math.functions;

import java.util.Scanner;

public class App {
    
    public static void mainMenu() {
        Scanner scan = new Scanner(System.in);
        int pilihan;
        System.out.println("==============================");
        System.out.println("Kasus minggu ke-2 hari pertama");
        System.out.println("==============================");
        System.out.println("[1] Math Functions");
        System.out.println("[2] Account Analytics");
        System.out.println("[3] Sum of Squares");
        System.out.println("[4] Crazy Lambdas");
        System.out.println("[5] Exit");
        pilihan = scan.nextInt();
        switch (pilihan) {
            case 1:
                AppMenu o1 = new AppMenu();
                o1.menu();;
                break;
            case 2:
                mainMenu();
                break;
            case 3:
                mainMenu();
                break;
            case 4:
                mainMenu();
                break;
            case 5:
                System.out.println("Terima Kasih");
                System.exit(0);
            default:
                System.out.println("Angka yang Anda masukkan tidak valid");
                mainMenu();
                break;
        }
    
    }

    public static void main(String[] args) {
        mainMenu();        
        /* System.out.println(new App().getGreeting());
        System.out.println(new App().fungsiKuadrat(3)); 
        System.out.println(new App().fungsiAbsolute(-968687));
        System.out.println(new App().fungsiIncrement(-10)); */
    }
}
