/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kasus;

import kasus.dua.*;
import kasus.satu.*;
import java.io.IOException;
import java.util.Scanner;

public class App {
    
    public static void pilihSatu() throws IOException {
        Short pilihan;
        Scanner scan = new Scanner(System.in);
        try {
            System.out.println("==============================");
            System.out.println("Create JSON or XML file");
            System.out.println("==============================");
            System.out.println("[1] Create JSON file");
            System.out.println("[2] Create XML file");
            System.out.println("[3] Back");
            System.out.println("[4] Exit");
            pilihan = (short) scan.nextInt();
            switch (pilihan) {
            case 1:
                JsonRead o1 = new JsonRead();
                o1.mulai();
                App.pilihSatu();
                break;
            case 2:
                XmlGenerator o2 = new XmlGenerator();
                o2.mulai();
                App.pilihSatu();
                break;
            case 3:
                System.out.println("tiga");
                App.menu();
                break;
            case 4:
                System.out.println("Terima Kasih");
                System.exit(0);
            default:
                System.out.println("Angka yang Anda masukkan tidak valid");
                App.menu();
                break;
            }
        } catch (Exception e) {
            
            System.out.println("Angka yang Anda masukkan tidak valid");
            App.menu();
        }
    }

    public static void pilihDua() throws IOException {
        Short pilihan;
        Scanner scan = new Scanner(System.in);
        try {
            System.out.println("==============================");
            System.out.println("Read JSON or XML file");
            System.out.println("==============================");
            System.out.println("[1] Read JSON file");
            System.out.println("[2] Read XML file");
            System.out.println("[3] Back");
            System.out.println("[4] Exit");
            pilihan = (short) scan.nextInt();
            switch (pilihan) {
            case 1:
                JsonRead o1 = new JsonRead();
                o1.mulai();
                App.pilihDua();
                break;
            case 2:
                XmlDomRead o2 = new XmlDomRead();
                o2.mulai();
                App.pilihDua();
                break;
            case 3:
                System.out.println("tiga");
                App.menu();
                break;
            case 4:
                System.out.println("Terima Kasih");
                System.exit(0);
            default:
                System.out.println("Angka yang Anda masukkan tidak valid");
                App.menu();
                break;
            }
        } catch (Exception e) {
            
            System.out.println("Angka yang Anda masukkan tidak valid");
            App.menu();
        }
        
    }
    
    public static void menu() throws IOException {
        Short pilihan;
        Scanner scan = new Scanner(System.in);
        try {
            System.out.println("==============================");
            System.out.println("Kasus minggu pertama hari ke-5");
            System.out.println("==============================");
            System.out.println("[1] Create JSON or XML file");
            System.out.println("[2] Read JSON or XML file");
            System.out.println("[3] XML vs JSON");
            System.out.println("[4] Exit");
            pilihan = (short) scan.nextInt();
            switch (pilihan) {
            case 1:
                App.pilihSatu();
                break;
            case 2:
                App.pilihDua();
                break;
            case 3:
                System.out.println("tiga");
                App.menu();
                break;
            case 4:
                System.exit(0);
            default:
                System.out.println("Angka yang Anda masukkan tidak valid");
                App.menu();
                break;
            }
        } catch (Exception e) {
            
            System.out.println("Angka yang Anda masukkan tidak valid");
            App.menu();
        }
        
    }

    public static void main(String[] args) throws IOException {
        App.menu();
    }
}
