/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kasus;

import kasus.Model.Bicycle;
import kasus.View.BicycleView;
import kasus.Controller.BicycleController;
import java.util.List;
import java.util.ArrayList;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        //fetch student record based on his roll no from the database
        Bicycle model  = retriveBicycleFromDatabase();

        //Create a view : to write student details on console
        BicycleView view = new BicycleView();

        BicycleController controller = new BicycleController(model, view);

        controller.updateView();

        //update model data
        
        controller.setBicycleCadence(133);
        controller.setBicycleGear(1455);

        controller.updateView();
   }

   private static Bicycle retriveBicycleFromDatabase(){
      List<Bicycle> bicycles = new ArrayList<>();
      bicycles.add(new Bicycle());      
      bicycles.add(new Bicycle());
      return bicycles;
   }
}
